version: '3.9'

services:
  redis:
    image: redis:5.0.0
    container_name: spring-redis
    command: redis-server
    volumes:
      - redis-data:/data/redis
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:5.0

    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_DATABASE=mongo-demo

volumes:
  mongo-data:
  redis-data: